Added support for HH:MM:SS time syntax

diff --git a/bin/cropdetect b/bin/cropdetect
--- a/bin/cropdetect
+++ b/bin/cropdetect
@@ -1,13 +1,13 @@
 #!/usr/bin/env bash
 #
 # Created:         Mo 2020-05-11 01:00:51 CEST
-# Last Modified:   Di 2020-07-14 13:51:13 CEST
+# Last Modified:   Di 2021-08-17 14:02:20 CEST
 #
 # cropdetect:
 #   This script detects crop margins of videos.
 
 # Help text
-usage() {
+usage () {
 cat << EOF
 
 Usage: cropdetect <inputfile>
@@ -20,8 +20,6 @@ EOF
 }
 
 # Initialization
-SS=
-T=
 FFMPEG=$(command -v ffmpeg)
 FFPROBE=$(command -v ffprobe)
 
@@ -30,9 +28,9 @@ while getopts "s:t:h" OPTION
 do
     case "$OPTION"
     in
-        s)  SS=$OPTARG
+        s)  SS="$OPTARG"
             ;;
-        t)  T=$OPTARG
+        t)  T="$OPTARG"
             ;;
         h)  usage
             exit 0
@@ -44,22 +42,59 @@ do
 done
 
 # Check if ffmpeg is available
-if [ ! -x "${FFMPEG}" ]
+if [ ! -x "$FFMPEG" ]
 then
     echo "$0: ffmpeg not found, probably not installed"
     exit 1
 fi
 
 # Check if ffprobe is available
-if [ ! -x "${FFPROBE}" ]
+if [ ! -x "$FFPROBE" ]
 then
     echo "$0: ffprobe not found, probably not installed"
     exit 1
 fi
 
-# Assert positive floating point numbers
-[ -z "$SS" ] || (( $(echo "$SS > 0" | bc -l) )) || exit 2
-[ -z "$T" ]  || (( $(echo "$T  > 0" | bc -l) )) || exit 3
+# Regular expressions for timestamps
+regex1='^[0-9]+(\.[0-9]+)?$'
+regex2='^[0-9]+:[0-5][0-9](\.[0-9]+)?$'
+regex3='^[0-9]+:([0-5][0-9]|2[0-3]):[0-5][0-9](\.[0-9]+)?$'
+
+# convert-a-duration-hhmmss-to-seconds-in-bash
+# https://stackoverflow.com/questions/18149127/convert-a-duration-hhmmss-to-seconds-in-bash
+to_seconds () {
+    echo "$1" | awk -F':' '{if (NF == 1) { print $1 } else if (NF == 2) { print $1*60 + $2 } else if (NF == 3) { print $1*3600 + $2*60 + $3 }}'
+}
+
+# Pattern matching for SS
+if [[ "$SS" =~ $regex1 ]] || [[ "$SS" =~ $regex2 ]] || [[ "$SS" =~ $regex3 ]]
+then
+    # Convert HH:MM:SS.sss to seconds
+    SS=$(to_seconds "$SS")
+
+elif [ -n "$SS" ]
+then
+    # Invalid pattern match, SS is not null and not empty
+    echo "$0: Invalid starting time"
+    exit 2
+fi
+
+
+# Pattern matching for T
+if [[ "$T" =~ $regex1 ]] || [[ "$T" =~ $regex2 ]] || [[ "$T" =~ $regex3 ]]
+then
+    # Convert HH:MM:SS.sss to seconds
+     T=$(to_seconds "$T")
+
+elif [ -n "$T" ]
+then
+    # Invalid pattern match, T is not null and not empty
+    echo "$0: Invalid termination time"
+    exit 3
+fi
+
+#echo "SS = $SS"
+#echo "T  = $T"
 
 # Skip options and shift index
 shift $((OPTIND-1))
@@ -69,7 +104,7 @@ while [ $# -gt 0 ]
 do
 
     # get filename
-    infile=$1
+    infile="$1"
     shift
 
     # Skip file if not existing
@@ -93,19 +128,19 @@ do
     if [ -z "$SS" ] && [ -z "$T" ]
     then
         # Empty starting and termination time
-        T0=$( echo "$dur*0.02" | bc -l )
-        T1=$( echo "$dur*0.05" | bc -l )
+        T0=$(echo "$dur*0.02" | bc -l)
+        T1=$(echo "$dur*0.05" | bc -l)
 
     elif [ -z "$T" ]
     then
         # Empty termination time
         T0="$SS"
-        T1=$( echo "$SS+$dur*0.03" | bc -l )
+        T1=$(echo "$SS+$dur*0.03" | bc -l)
 
     elif [ -z "$SS" ]
     then
         # Empty starting time
-        T0=$( echo "$T-$dur*0.03" | bc -l )
+        T0=$(echo "$T-$dur*0.03" | bc -l)
         T1="$T"
 
     else
@@ -121,9 +156,9 @@ do
     (( $(echo "$T0 < $T1"  | bc -l) )) || T0=0
 
     # Grep crop geometry
-    result=$($FFMPEG -ss "${T0}" -i "${infile}" -t "$T1" -vsync vfr -vf fps=1/2,cropdetect -f null - 2>&1 | awk '/crop/ { print $NF }' | tr ' ' '\n' | sort | uniq -c | sort -n | tail -1 | awk '{ print $NF }')
+    result=$($FFMPEG -ss "$T0" -i "$infile" -t "$T1" -vsync vfr -vf fps=1/2,cropdetect -f null - 2>&1 | awk '/crop/ { print $NF }' | tr ' ' '\n' | sort | uniq -c | sort -n | tail -1 | awk '{ print $NF }')
 
     # Check result string
-    [ -n "${result}" ] && echo "${result}" || exit 4
+    [ -n "$result" ] && echo "$result" || exit 4
 
 done
